[package]
name = "zed-tooling-language-server"
version = "0.1.0"
edition = "2021"
publish = false
license = "MPL-2.0"

[lib]
path = "src/tooling-language-server.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.2.0"
