[package]
name = "tooling-language-server"
version = "0.2.0"
edition = "2021"
description = "A language server for tooling"
keywords = ["lsp", "language-server", "tower"]
categories = ["asynchronous"]
repository = "https://github.com/filiptibell/tooling-language-server"
license = "MPL-2.0"
publish = false

[[bin]]
name = "tooling-language-server"
path = "src/main.rs"

[profile.release]
opt-level = "z"
strip = true
lto = true

[dependencies]
bytes = "1.0"
dashmap = "5.5"
logos = "0.13"
once_cell = "1.18"
semver = "1.0"
thiserror = "1.0"
url = "2.4"

async-channel = "1.9"
async-semaphore = "1.2"
futures = "0.3"

serde = "1.0"
serde_json = "1.0"
toml = "0.8"

taplo = "0.12"
json-syntax = "0.10"
locspan = "0.8"

moka = { version = "0.12", features = ["future"] }

tokio = { version = "1.25", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dependencies.tower-lsp]
version = "0.20"
default-features = false
features = ["runtime-tokio", "proposed"]

[dependencies.lsp-document]
git = "https://github.com/artempyanykh/rust-lsp-document"
rev = "d08ce4d2e36b073611d0db17e5a2b41a70d8daa4"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "gzip"]

[dependencies.clap]
version = "4.4"
features = ["derive", "env"]
