[package]
name = "tooling-language-server"
version = "0.0.1"
edition = "2021"
description = "A language server for tooling"
keywords = ["lsp", "language-server", "tower"]
categories = ["asynchronous"]
repository = "https://github.com/filiptibell/tooling-language-server"
license = "MPL-2.0"
publish = false

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
itertools = "0.11"
logos = "0.13"
octocrab = "0.29"
regex = "1.9"
semver = "1.0"
thiserror = "1.0"

futures = "0.3"
tokio = { version = "1.27", features = ["full"] }
tokio-util = { version = "0.7", default-features = false, features = [
    "compat",
] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

tower-lsp = { version = "0.20", features = ["proposed"] }

clap = { version = "4.4", features = ["derive", "env"] }

serde = "1.0"
serde_json = "1.0"
