[package]
name = "tooling-language-server"
version = "0.0.1"
edition = "2021"
description = "A language server for tooling"
keywords = ["lsp", "language-server", "tower"]
categories = ["asynchronous"]
repository = "https://github.com/filiptibell/tooling-language-server"
license = "MPL-2.0"
publish = false

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
bytes = "1.0"
futures = "0.3"
logos = "0.13"
once_cell = "1.18"
semver = "1.0"
taplo = "0.12"
thiserror = "1.0"

serde = "1.0"
serde_json = "1.0"
toml = "0.7"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

moka = { version = "0.11", features = ["future"] }

[dependencies.tokio]
version = "1.27"
default-features = false
features = ["fs", "io-std", "net", "rt-multi-thread", "sync", "time"]

[dependencies.tokio-util]
version = "0.7"
default-features = false
features = ["compat"]

[dependencies.tower-lsp]
version = "0.20"
features = ["proposed"]

[dependencies.lsp-document]
git = "https://github.com/artempyanykh/rust-lsp-document"
rev = "d08ce4d2e36b073611d0db17e5a2b41a70d8daa4"

[dependencies.reqwest]
version = "0.11"
features = ["rustls-tls"]

[dependencies.clap]
version = "4.4"
features = ["derive", "env"]
