[package]
name = "tooling-language-server"
version = "0.0.4"
edition = "2021"
description = "A language server for tooling"
keywords = ["lsp", "language-server", "tower"]
categories = ["asynchronous"]
repository = "https://github.com/filiptibell/tooling-language-server"
license = "MPL-2.0"
publish = false

[[bin]]
name = "tooling-language-server"
path = "src/main.rs"

[profile.release]
opt-level = "z"
strip = true
lto = true

[dependencies]
bytes = "1.0"
dashmap = "5.5"
logos = "0.13"
once_cell = "1.18"
semver = "1.0"
smol = "1.3"
taplo = "0.12"
thiserror = "1.0"
url = "2.4"

async-channel = "1.9"
async-lock = "2.8"
futures-lite = "1.13"

http-types = "2.12"
async-h1 = "2.3"
async-native-tls = "0.5"

serde = "1.0"
serde_json = "1.0"
toml = "0.8"

moka = { version = "0.11", features = ["future"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dependencies.tower-lsp]
version = "0.20"
default-features = false
features = ["runtime-agnostic", "proposed"]

[dependencies.lsp-document]
git = "https://github.com/artempyanykh/rust-lsp-document"
rev = "d08ce4d2e36b073611d0db17e5a2b41a70d8daa4"

[dependencies.clap]
version = "4.4"
features = ["derive", "env"]
