[package]
name = "tooling-language-server"
version = "0.0.1"
edition = "2021"
description = "A language server for tooling"
keywords = ["lsp", "language-server", "tower"]
categories = ["asynchronous"]
repository = "https://github.com/filiptibell/tooling-language-server"
license = "MPL-2.0"
publish = false

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
itertools = "0.11.0"
logos = "0.13"
octocrab = "0.29"
regex = "1.9"
semver = "1.0"
thiserror = "1.0"

async-lsp = { version = "0.0.5", features = ["tokio"] }
lsp-types = { version = "0.94", features = ["proposed"] }

tokio = { version = "1.27", features = ["full"] }
futures = "0.3"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

tower = "0.4"
tower-layer = "0.3"
tower-service = "0.3"

serde = "1.0"
serde_json = "1.0"

[target.'cfg(not(unix))'.dependencies]
tokio-util = { version = "0.7", default-features = false, features = [
    "compat",
] }
