[package]
name = "versioning"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

[lib]
name = "versioning"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
semver = "1.0"
